services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/traefik.yaml:ro
      - ./acme.json:/acme.json
      - ./dynamic:/dynamic
    networks:
      - proxy
      - web
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      
      # Dashboard
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN:-example.com}`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.middlewares=traefik-auth"
      
      # Basic Auth for Dashboard (will be set via environment variable)
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_AUTH}"

networks:
  proxy:
    external: true
  web:
    external: true
