services:
  my-nextjs-app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        NEXT_PUBLIC_IMGPROXY_BASE: ${NEXT_PUBLIC_IMGPROXY_BASE}
        NEXT_PUBLIC_S3_ENDPOINT: ${NEXT_PUBLIC_S3_ENDPOINT}
        NEXT_PUBLIC_S3_BUCKET: ${NEXT_PUBLIC_S3_BUCKET}
        NEXT_PUBLIC_GTM_ID: ${NEXT_PUBLIC_GTM_ID}
    container_name: my-nextjs-app

    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      PORT: "3004"
      NEXT_TELEMETRY_DISABLED: "1"
      DATABASE_URL: ${DATABASE_URL}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}

    expose:
      - "3004"
    restart: unless-stopped
    networks: [proxy, appnet]

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      # main domain
      - "traefik.http.routers.my-nextjs-app.rule=Host(`app.example.com`)"
      - "traefik.http.routers.my-nextjs-app.entrypoints=websecure"
      - "traefik.http.routers.my-nextjs-app.tls=true"
      - "traefik.http.routers.my-nextjs-app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.my-nextjs-app.service=my-nextjs-app-svc"

      # service port
      - "traefik.http.services.my-nextjs-app-svc.loadbalancer.server.port=3004"
      - "traefik.http.services.my-nextjs-app-svc.loadbalancer.passhostheader=true"

      # www redirect
      - "traefik.http.routers.my-nextjs-app-www.rule=Host(`www.app.example.com`)"
      - "traefik.http.routers.my-nextjs-app-www.entrypoints=websecure"
      - "traefik.http.routers.my-nextjs-app-www.tls=true"
      - "traefik.http.routers.my-nextjs-app-www.tls.certresolver=letsencrypt"
      - "traefik.http.routers.my-nextjs-app-www.middlewares=my-nextjs-app-redirect@docker"
      - "traefik.http.middlewares.my-nextjs-app-redirect.redirectregex.regex=^https?://www\\.app\\.example\\.com(.*)"
      - "traefik.http.middlewares.my-nextjs-app-redirect.redirectregex.replacement=https://app.example.com$1"
      - "traefik.http.middlewares.my-nextjs-app-redirect.redirectregex.permanent=true"

networks:
  proxy:
    external: true
  appnet:
    external: true